"""Type stubs for numpy - minimal."""
from typing import Any

__all__: Any
array: Any
ndarray: Any

# These are complex type stubs - just use Any for now
def array(*args: Any, **kwargs: Any) -> Any: ...
def isnan(x: Any) -> Any: ...
def isinf(x: Any) -> Any: ...
def isfinite(x: Any) -> Any: ...
def min(x: Any, *args: Any, **kwargs: Any) -> Any: ...
def max(x: Any, *args: Any, **kwargs: Any) -> Any: ...
def sum(x: Any, *args: Any, **kwargs: Any) -> Any: ...
def abs(x: Any) -> Any: ...
def radians(x: Any) -> Any: ...
def cos(x: Any) -> Any: ...

# ndarray type
class ndarray:
    shape: Any
    dtype: Any
    def astype(self, *args: Any, **kwargs: Any) -> Any: ...


