"""
Region adjacency data - which regions border which.

This data is used by the viewer to show clickable neighbor labels at region edges.
Format: {region_id: {direction: neighbor_region_id}}
Directions: 'north', 'south', 'east', 'west'

IMPORTANT: This module loads data from generated/regions/region_adjacency.json which is
generated by compute_adjacency.py or export_adjacency.py. To update adjacency data:
1. Add/update regions in src/regions_config.py
2. Run: python compute_adjacency.py
3. The generated JSON file is automatically used here

The generator:
- Uses Natural Earth 10m boundary data
- Excludes corner-only touches (like Four Corners)
- Includes all edge-sharing borders
- Determines direction based on state centroids
"""

import json
from pathlib import Path
from typing import Dict, Any

# Load adjacency data from generated JSON file
_ADJACENCY_FILE = Path(__file__).parent.parent / 'generated' / 'regions' / 'region_adjacency.json'

try:
    with open(_ADJACENCY_FILE) as f:
        REGION_ADJACENCY = json.load(f)
except FileNotFoundError:
    print(f"Warning: Adjacency data file not found: {_ADJACENCY_FILE}")
    print("Run 'python compute_adjacency.py' to generate it.")
    REGION_ADJACENCY = {}

# Legacy aliases for backward compatibility
US_STATE_ADJACENCY: Dict[str, Dict[str, str]] = {
    k: v for k, v in REGION_ADJACENCY.items()
    if k in [
        'alabama', 'alaska', 'arizona', 'arkansas', 'california', 'colorado',
        'connecticut', 'delaware', 'florida', 'georgia', 'hawaii', 'idaho',
        'illinois', 'indiana', 'iowa', 'kansas', 'kentucky', 'louisiana',
        'maine', 'maryland', 'massachusetts', 'michigan', 'minnesota',
        'mississippi', 'missouri', 'montana', 'nebraska', 'nevada',
        'new_hampshire', 'new_jersey', 'new_mexico', 'new_york',
        'north_carolina', 'north_dakota', 'ohio', 'oklahoma', 'oregon',
        'pennsylvania', 'rhode_island', 'south_carolina', 'south_dakota',
        'tennessee', 'texas', 'utah', 'vermont', 'virginia', 'washington',
        'west_virginia', 'wisconsin', 'wyoming'
    ]
}

INTERNATIONAL_ADJACENCY: Dict[str, Dict[str, str]] = {
    k: v for k, v in REGION_ADJACENCY.items()
    if k not in US_STATE_ADJACENCY
}


def get_adjacency_data() -> Dict[str, Any]:
    """
    Export adjacency data as JSON-compatible dict for the viewer.
    Returns: {region_id: {direction: neighbor_region_id}}
    """
    return REGION_ADJACENCY


if __name__ == '__main__':
    import json
    print(json.dumps(get_adjacency_data(), indent=2))
